library(readr)
library(lubridate)
library(dplyr)
library(magrittr)
library(stringr)
library(ggplot2)

library(readr)
# this is a line from rstudio
statement <- read_delim("Statement.csv", 
                        delim = "|", escape_double = FALSE, trim_ws = TRUE, 
                        skip = 2)
statement2 <- read_delim("Statement (1).csv", 
                         delim = "|", escape_double = FALSE, col_names = FALSE, 
                         locale = locale(), trim_ws = TRUE, skip = 3)

colnames(statement) <- c("transaction_date", "type", "description", "pmt_number", "bank_reference", "amount")
colnames(statement2) <- c("transaction_date", "type", "description", "pmt_number", "bank_reference", "amount")
statement <- rbind(statement, statement2)

View(statement)

# bank_stmt <- statement %>% filter(!is.na(transaction_date))


# Helper function

is_keyword_in<- function(column, keyword){
  is_string_in_word <- ifelse(max(str_detect(column,as.character(keyword))) > 0, 1, 0)
  return(is_string_in_word)
}

is_keyword_in('milapicalulu','lulu')
is_keyword_in('milapicalulu','ganbei')

# Keyword search

Encoding(statement$type)<-'latin1'
# bank_stmt <- statement %>% filter(!is.na(transaction_date))


bank_stmt <- statement %>% filter(!is.na(transaction_date)) %>% 
  mutate(
    amount = abs(amount),
    amount = case_when(type == 'ATGRIEZTS PIRKUMS' ~ amount*(-1), T~ amount),
    transaction_date = dmy(transaction_date),
    transaction_week = week(transaction_date),
    transaction_month = month(transaction_date, label = T),
    transaction_yearmonth = floor_date(transaction_date,unit = 'month'),
    description_f = str_replace_all(tolower(gsub('[[:punct:]]|[[:digit:]]', '', description)), pattern=" ", repl=""),
    category = case_when(
      type %in% c('SKAIDRAS NAUDAS IZÒEMÐANA',
                  'SKAIDRAS NAUDAS IZ\xd2EM\xd0ANA')~ 'Cash withdrawal',
      type %in% c('IENÂKOÐAIS ZIBMAKSÂJUMS',
                  'IENÂKOÐAIS MAKSÂJUMS',
                  'IENÂKOÐAIS EKS MAKSÂJUMS',
                  'IEN\\\xc2KO\\\xd0AIS MAKS\\\xc2JUMS',
                  'IEN\xc2KO\xd0AIS EKS MAKS\xc2JUMS',
                  'IEN\\\xc2KO\\\xd0AIS ZIBMAKS\\\xc2JUMS') ~ 'Incoming',
      type %in% c('DEBETA PROCENTI',
                  'MAKSA PAR SK.NAUDAS IZÒEMÐANU', 
                  'ÂTRÂ MAKSÂJUMA KOMISIJA',
                  'MAKSA PAR SK.NAUDAS IZ\xd2EM\xd0ANU',
                  'MAKSA PAR KARTI')~ 'Commisions',
      description_f == 'ref' ~ 'Commisions',
      sapply(description_f,function(x) is_keyword_in(x,'vitalijsgrundsteins')) > 0 ~ 'Incoming',
      sapply(description_f,function(x) is_keyword_in(x,'wolt')) > 0 ~ 'Wolt',
      sapply(description_f,function(x) is_keyword_in(x,'bolt')) > 0 ~ 'Bolt',
      sapply(description_f,function(x) is_keyword_in(x,'wwwalv')) > 0 ~ 'Online shopping',
      sapply(description_f,function(x) is_keyword_in(x,'restart')) > 0 ~ 'Restart',
      sapply(description_f,function(x) is_keyword_in(x,'narvesen')) > 0 ~ 'Narvesen',
      sapply(description_f,function(x) is_keyword_in(x,'rimi')) > 0 ~ 'Rimi',
      sapply(description_f,function(x) is_keyword_in(x,'troubadour')) > 0 ~ 'Cadets',
      sapply(description_f,function(x) is_keyword_in(x,'cadets')) > 0 ~ 'Cadets',
      sapply(description_f,function(x) is_keyword_in(x,'audible')) > 0 ~ 'Audible',
      sapply(description_f,function(x) is_keyword_in(x,'applecombill')) > 0 ~ 'Apple',
      sapply(description_f,function(x) is_keyword_in(x,'circlek')) > 0 ~ 'Circle K',
      sapply(description_f,function(x) is_keyword_in(x,'wwwlululv')) > 0 ~ 'Lulu',
      sapply(description_f,function(x) is_keyword_in(x,'maxima')) > 0 ~ 'Maxima',
      sapply(description_f,function(x) is_keyword_in(x,'strawberrie')) > 0 ~ 'Ogas',
      sapply(description_f,function(x) is_keyword_in(x,'factilejeopardy')) > 0 ~ 'Factile',
      sapply(description_f,function(x) is_keyword_in(x,'terra')) > 0 ~ 'Terra',
      sapply(description_f,function(x) is_keyword_in(x,'ziedusalons')) > 0 ~ 'Flowers',
      sapply(description_f,function(x) is_keyword_in(x,'zieduveikals')) > 0 ~ 'Flowers',
      sapply(description_f,function(x) is_keyword_in(x,'vocalmaster')) > 0 ~ 'Singing',
      sapply(description_f,function(x) is_keyword_in(x,'bookingcom')) > 0 ~ 'Booking',
      sapply(description_f,function(x) is_keyword_in(x,'makonis')) > 0 ~ 'Makonis',
      sapply(description_f,function(x) is_keyword_in(x,'drogas')) > 0 ~ 'Drogas',
      sapply(description_f,function(x) is_keyword_in(x,'herbarijs')) > 0 ~ 'Herbarijs',
      sapply(description_f,function(x) is_keyword_in(x,'adobecom')) > 0 ~ 'Adobe',
      sapply(description_f,function(x) is_keyword_in(x,'amazonprime')) > 0 ~ 'Amazon',
      sapply(description_f,function(x) is_keyword_in(x,'galerijacentrshm')) > 0 ~ 'H&M',
      sapply(description_f,function(x) is_keyword_in(x,'siafitpeople')) > 0 ~ 'PeopleFitness',
      sapply(description_f,function(x) is_keyword_in(x,'gimlet')) > 0 ~ 'Gimlet',
      sapply(description_f,function(x) is_keyword_in(x,'stauere')) > 0 ~ 'Self Transfer',
      sapply(description_f,function(x) is_keyword_in(x,'thevillagecoconut')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'kiwi')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'danielakortina')) > 0 ~ 'Rent',
      sapply(description_f,function(x) is_keyword_in(x,'bangkok')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'stockman')) > 0 ~ 'Stockman',
      sapply(description_f,function(x) is_keyword_in(x,'elkor')) > 0 ~ 'Elkor',
      sapply(description_f,function(x) is_keyword_in(x,'rigalvatm')) > 0 ~ 'ATM',
      sapply(description_f,function(x) is_keyword_in(x,'travelstart')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'peekandcloppenburg')) > 0 ~ 'Peek and Cloppenburg',
      sapply(description_f,function(x) is_keyword_in(x,'paypalpowair')) > 0 ~ 'V airsoft',
      sapply(description_f,function(x) is_keyword_in(x,'paypalpaintball')) > 0 ~ 'V airsoft',
      sapply(description_f,function(x) is_keyword_in(x,'phuket')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'paypalsiaglamorallv')) > 0 ~ 'Amoralle',
      sapply(description_f,function(x) is_keyword_in(x,'jetair')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'intheair')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'steezystudio')) > 0 ~ 'Steezystudio',
      sapply(description_f,function(x) is_keyword_in(x,'morex')) > 0 ~ 'Online shopping',
      sapply(description_f,function(x) is_keyword_in(x,'ikea')) > 0 ~ 'Ikea',
      sapply(description_f,function(x) is_keyword_in(x,'airport')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'arlandatp')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'wowbeauty')) > 0 ~ 'WOW',
      sapply(description_f,function(x) is_keyword_in(x,'paypalcdkeys')) > 0 ~ 'Games',
      sapply(description_f,function(x) is_keyword_in(x,'paypaljonathanl')) > 0 ~ 'Poker',
      sapply(description_f,function(x) is_keyword_in(x,'rozvadov')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'wwwasoscom')) > 0 ~ 'Asos',
      sapply(description_f,function(x) is_keyword_in(x,'paypalroaringtop')) > 0 ~ 'V airsoft',
      sapply(description_f,function(x) is_keyword_in(x,'veikalssportsdirect')) > 0 ~ 'Shopping',
      sapply(description_f,function(x) is_keyword_in(x,'mistersbobs')) > 0 ~ 'Lunch at work',
      sapply(description_f,function(x) is_keyword_in(x,'kafejnicasala')) > 0 ~ 'Lunch at work',
      sapply(description_f,function(x) is_keyword_in(x,'hsreplaynet')) > 0 ~ 'Subscriptions',
      sapply(description_f,function(x) is_keyword_in(x,'yandex')) > 0 ~ 'Yandex',
      sapply(description_f,function(x) is_keyword_in(x,'labaspreces')) > 0 ~ 'LabasPreces',
      sapply(description_f,function(x) is_keyword_in(x,'peterclarke')) > 0 ~ 'Poker',
      sapply(description_f,function(x) is_keyword_in(x,'manslmt')) > 0 ~ 'PhoneBill',
      sapply(description_f,function(x) is_keyword_in(x,'indexo')) > 0 ~ 'Pension',
      sapply(description_f,function(x) is_keyword_in(x,'lakstos')) > 0 ~ 'Flowers',
      sapply(description_f,function(x) is_keyword_in(x,'frizetava')) > 0 ~ 'Hairdresser',
      sapply(description_f,function(x) is_keyword_in(x,'mango')) > 0 ~ 'Mango',
      sapply(description_f,function(x) is_keyword_in(x,'zimolaveikals')) > 0 ~ 'Gifts',
      sapply(description_f,function(x) is_keyword_in(x,'amoralle')) > 0 ~ 'Amoralle',
      sapply(description_f,function(x) is_keyword_in(x,'icard')) > 0 ~ 'Poker',
      sapply(description_f,function(x) is_keyword_in(x,'upswingpoker')) > 0 ~ 'Poker',
      sapply(description_f,function(x) is_keyword_in(x,'cardrunnersev')) > 0 ~ 'Poker',
      sapply(description_f,function(x) is_keyword_in(x,'gmtbeauty')) > 0 ~ 'Gifts',
      sapply(description_f,function(x) is_keyword_in(x,'sexystyle')) > 0 ~ 'Sexystyle',
      sapply(description_f,function(x) is_keyword_in(x,'zaraveikals')) > 0 ~ 'Zara',
      sapply(description_f,function(x) is_keyword_in(x,'vinastudija')) > 0 ~ 'Gifts',
      sapply(description_f,function(x) is_keyword_in(x,'lashandbrow')) > 0 ~ 'Beauty',
      sapply(description_f,function(x) is_keyword_in(x,'pokercoaching')) > 0 ~ 'Poker',
      sapply(description_f,function(x) is_keyword_in(x,'elgarsozolins')) > 0 ~ 'Rent',
      sapply(description_f,function(x) is_keyword_in(x,'accessorize')) > 0 ~ 'Accessorize',
      sapply(description_f,function(x) is_keyword_in(x,'mango')) > 0 ~ 'Mango',
      sapply(description_f,function(x) is_keyword_in(x,'douglas')) > 0 ~ 'Douglas',
      sapply(description_f,function(x) is_keyword_in(x,'bilesuserviss')) > 0 ~ 'Bilesuserviss',
      sapply(description_f,function(x) is_keyword_in(x,'ledusskola')) > 0 ~ 'LedusSkola',
      sapply(description_f,function(x) is_keyword_in(x,'psxlv')) > 0 ~ 'Gifts',
      sapply(description_f,function(x) is_keyword_in(x,'aseimriga')) > 0 ~ 'Apavi40plus',
      sapply(description_f,function(x) is_keyword_in(x,'ilgvarslaganovskis')) > 0 ~ 'Transfers',
      sapply(description_f,function(x) is_keyword_in(x,'galleriarigahm')) > 0 ~ 'H&M',
      sapply(description_f,function(x) is_keyword_in(x,'foodfactory')) > 0 ~ 'FoodFactory',
      sapply(description_f,function(x) is_keyword_in(x,'einarsbirkhans')) > 0 ~ 'DrivingLessons',
      sapply(description_f,function(x) is_keyword_in(x,'akropole')) > 0 ~ 'Akropole',
      sapply(description_f,function(x) is_keyword_in(x,'domina')) > 0 ~ 'Domina',
      sapply(description_f,function(x) is_keyword_in(x,'valtersunrapa')) > 0 ~ 'Books',
      sapply(description_f,function(x) is_keyword_in(x,'janisroze')) > 0 ~ 'Books',
      sapply(description_f,function(x) is_keyword_in(x,'crushlive')) > 0 ~ 'Poker',
      sapply(description_f,function(x) is_keyword_in(x,'carrot')) > 0 ~ 'Poker',
      sapply(description_f,function(x) is_keyword_in(x,'hotelsanpimilano')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'viesnicaelizabet')) > 0 ~ 'Hotel',
      sapply(description_f,function(x) is_keyword_in(x,'radissonlatvija')) > 0 ~ 'Hotel',
      sapply(description_f,function(x) is_keyword_in(x,'eraesthetic')) > 0 ~ 'Eraesthetic',
      sapply(description_f,function(x) is_keyword_in(x,'smartpostlvtallin')) > 0 ~ 'Zalando',
      sapply(description_f,function(x) is_keyword_in(x,'premiummedical')) > 0 ~ 'PremiumMedical',
      sapply(description_f,function(x) is_keyword_in(x,'ryanair')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'zalando')) > 0 ~ 'Zalando',
      sapply(description_f,function(x) is_keyword_in(x,'euronics')) > 0 ~ 'Euronics',
      sapply(description_f,function(x) is_keyword_in(x,'ryanair')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'bistrovermanitis')) > 0 ~ 'Lido',
      sapply(description_f,function(x) is_keyword_in(x,'lidovermanitis')) > 0 ~ 'Lido',
      sapply(description_f,function(x) is_keyword_in(x,'latloto')) > 0 ~ 'Latloto',
      sapply(description_f,function(x) is_keyword_in(x,'nordvpn')) > 0 ~ 'Nordvpn',
      sapply(description_f,function(x) is_keyword_in(x,'elektrum')) > 0 ~ 'Electricity',
      sapply(description_f,function(x) is_keyword_in(x,'rekinsnrdziksterbatasnams')) > 0 ~ 'Utilities',
      sapply(description_f,function(x) is_keyword_in(x,'benuaptieka')) > 0 ~ 'Benuaptieka',
      sapply(description_f,function(x) is_keyword_in(x,'dropbox')) > 0 ~ 'Dropbox',
      sapply(description_f,function(x) is_keyword_in(x,'manstet')) > 0 ~ 'TET',
      sapply(description_f,function(x) is_keyword_in(x,'dropbox')) > 0 ~ 'Dropbox',
      sapply(description_f,function(x) is_keyword_in(x,'algusaraksts')) > 0 ~ 'Salary',
      sapply(description_f,function(x) is_keyword_in(x,'avansusaraksts')) > 0 ~ 'Salary',
      sapply(description_f,function(x) is_keyword_in(x,'londongates')) > 0 ~ 'Salary',
      sapply(description_f,function(x) is_keyword_in(x,'amazonvideo')) > 0 ~ 'Amazonvideo',
      sapply(description_f,function(x) is_keyword_in(x,'dtgorsctaizdevums')) > 0 ~ 'PC',
      sapply(description_f,function(x) is_keyword_in(x,'ezitismig')) > 0 ~ 'Ezitismigla',
      sapply(description_f,function(x) is_keyword_in(x,'revolut')) > 0 ~ 'Revolut',
      sapply(description_f,function(x) is_keyword_in(x,'kukotava')) > 0 ~ 'Kukotava',
      sapply(description_f,function(x) is_keyword_in(x,'secretscentbox')) > 0 ~ 'Secretscentbox',
      sapply(description_f,function(x) is_keyword_in(x,'ksenukai')) > 0 ~ 'Ksenukai',
      sapply(description_f,function(x) is_keyword_in(x,'hotelneufeldzurichc')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'ticketmasterschweizag')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'reserved')) > 0 ~ 'Reserved',
      sapply(description_f,function(x) is_keyword_in(x,'viasms')) > 0 ~ 'Debt',
      sapply(description_f,function(x) is_keyword_in(x,'donnaveikals')) > 0 ~ 'Donnaveikals',
      sapply(description_f,function(x) is_keyword_in(x,'skinprolazer')) > 0 ~ 'Skinpro',
      sapply(description_f,function(x) is_keyword_in(x,'capitalclinic')) > 0 ~ 'Capitalclinic',
      sapply(description_f,function(x) is_keyword_in(x,'orderonlinemusketeers')) > 0 ~ 'Shroomshop',
      sapply(description_f,function(x) is_keyword_in(x,'kristianazelca')) > 0 ~ 'Photopgraphy',
      sapply(description_f,function(x) is_keyword_in(x,'beautymarket')) > 0 ~ 'Beautymarket',
      sapply(description_f,function(x) is_keyword_in(x,'kristianagalerijariga')) > 0 ~ 'Kristiana',
      sapply(description_f,function(x) is_keyword_in(x,'patreonmembership')) > 0 ~ 'Patreon',
      sapply(description_f,function(x) is_keyword_in(x,'mananakase')) > 0 ~ 'Manana',
      sapply(description_f,function(x) is_keyword_in(x,'patreonmembership')) > 0 ~ 'Patreon',
      sapply(description_f,function(x) is_keyword_in(x,'retaillogistics')) > 0 ~ 'PhoneBill',
      sapply(description_f,function(x) is_keyword_in(x,'gertrudescentrsriga')) > 0 ~ 'PhoneBill',
      sapply(description_f,function(x) is_keyword_in(x,'zurich')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'wwwekaselv')) > 0 ~ 'Ekase',
      sapply(description_f,function(x) is_keyword_in(x,'bilesuparadize')) > 0 ~ 'Bilesuparadize',
      sapply(description_f,function(x) is_keyword_in(x,'espariga')) > 0 ~ 'ESPA',
      sapply(description_f,function(x) is_keyword_in(x,'jysktcmols')) > 0 ~ 'Jysk',
      sapply(description_f,function(x) is_keyword_in(x,'palladiumpraha')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'iherbcom')) > 0 ~ 'Iherb',
      sapply(description_f,function(x) is_keyword_in(x,'balticticketing')) > 0 ~ 'Balticticketing',
      sapply(description_f,function(x) is_keyword_in(x,'podologijasakademija')) > 0 ~ 'Pedi',
      sapply(description_f,function(x) is_keyword_in(x,'wwwpiearsta')) > 0 ~ 'Pedi',
      sapply(description_f,function(x) is_keyword_in(x,'raimondsmantins')) > 0 ~ 'Transfers',
      sapply(description_f,function(x) is_keyword_in(x,'masazufabrika')) > 0 ~ 'Masazufabrika',
      sapply(description_f,function(x) is_keyword_in(x,'aparthotelplaza')) > 0 ~ 'Hotel',
      sapply(description_f,function(x) is_keyword_in(x,'vairksaulesvaldemr')) > 0 ~ 'vairksaules',
      sapply(description_f,function(x) is_keyword_in(x,'siactsal')) > 0 ~ 'Silvertree',
      sapply(description_f,function(x) is_keyword_in(x,'amznmktplace')) > 0 ~ 'AmazonMarketplace',
      sapply(description_f,function(x) is_keyword_in(x,'sportland')) > 0 ~ 'Sportland',
      sapply(description_f,function(x) is_keyword_in(x,'kfejnicadownstrretriga')) > 0 ~ 'Downstreet',
      sapply(description_f,function(x) is_keyword_in(x,'fosteriadafortunatamilano')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'electrolux')) > 0 ~ 'Electrolux',
      sapply(description_f,function(x) is_keyword_in(x,'milano')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'hairrigariga')) > 0 ~ 'Hairrigariga',
      sapply(description_f,function(x) is_keyword_in(x,'wwwmuzikasveikals')) > 0 ~ 'wwwmuzikasveikals',
      sapply(description_f,function(x) is_keyword_in(x,'vipagalleriariga')) > 0 ~ 'Vipa',
      sapply(description_f,function(x) is_keyword_in(x,'wwwziedotlv')) > 0 ~ 'wwwziedotlv',
      sapply(description_f,function(x) is_keyword_in(x,'depoveikals')) > 0 ~ 'Depo',
      sapply(description_f,function(x) is_keyword_in(x,'bellagio')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'andaluzijassun')) > 0 ~ 'andaluzijassuns',
      sapply(description_f,function(x) is_keyword_in(x,'easypothelsinki')) > 0 ~ 'Easypot',
      sapply(description_f,function(x) is_keyword_in(x,'mccrefwwwlvlt')) > 0 ~ '220LV',
      sapply(description_f,function(x) is_keyword_in(x,'mulberry')) > 0 ~ 'Mulberry',
      sapply(description_f,function(x) is_keyword_in(x,'trufit')) > 0 ~ 'Trufit',
      sapply(description_f,function(x) is_keyword_in(x,'tintorestorns')) > 0 ~ 'Tinto',
      sapply(description_f,function(x) is_keyword_in(x,'lidovrmantis')) > 0 ~ 'Lido',
      sapply(description_f,function(x) is_keyword_in(x,'rosemarinehelsink')) > 0 ~ 'Rosemarine',
      sapply(description_f,function(x) is_keyword_in(x,'mcdonaldsmereahelsinki')) > 0 ~ 'Wolt',
      sapply(description_f,function(x) is_keyword_in(x,'helsinkifi')) > 0 ~ 'Wolt',
      sapply(description_f,function(x) is_keyword_in(x,'andriskalnins')) > 0 ~ 'Transfers',
      sapply(description_f,function(x) is_keyword_in(x,'iljasurikovss')) > 0 ~ 'Transfers',
      sapply(description_f,function(x) is_keyword_in(x,'janistjarve')) > 0 ~ 'Transfers',
      sapply(description_f,function(x) is_keyword_in(x,'anetekleine')) > 0 ~ 'Transfers',
      sapply(description_f,function(x) is_keyword_in(x,'sunnybeautylounge')) > 0 ~ 'Sunnybeautylounge',
      sapply(description_f,function(x) is_keyword_in(x,'barcelona')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'siagkcoriga')) > 0 ~ 'Silicenko',
      sapply(description_f,function(x) is_keyword_in(x,'sweetdelights')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'bomondveikals')) > 0 ~ 'Bomond',
      sapply(description_f,function(x) is_keyword_in(x,'fabulousparisframount')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'ubertrip')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'ubereats')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'vapeschoppraha')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'bredovskydvurpraha')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'sephoragrandistapraha')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'omioberlin')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'royalcourthotelpraha')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'praha')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'notino')) > 0 ~ 'Notino',
      sapply(description_f,function(x) is_keyword_in(x,'olearysrigaplaza')) > 0 ~ 'Olearys',
      sapply(description_f,function(x) is_keyword_in(x,'kennysbookshop')) > 0 ~ 'Books',
      sapply(description_f,function(x) is_keyword_in(x,'rigaskebabs')) > 0 ~ 'Rigaskebabs',
      sapply(description_f,function(x) is_keyword_in(x,'wwwforumcinemas')) > 0 ~ 'Forumcinemas',
      sapply(description_f,function(x) is_keyword_in(x,'dinozoo')) > 0 ~ 'Dinozoo',
      sapply(description_f,function(x) is_keyword_in(x,'mccrefnyapelikanetoyfi')) > 0 ~ 'Arcade',
      sapply(description_f,function(x) is_keyword_in(x,'nikeoutletstore')) > 0 ~ 'Nikeoutletstore',
      sapply(description_f,function(x) is_keyword_in(x,'beautyfor')) > 0 ~ 'Beautyfor',
      sapply(description_f,function(x) is_keyword_in(x,'stblackteraseriga')) > 0 ~ 'stblackteraseriga',
      sapply(description_f,function(x) is_keyword_in(x,'sumupnnziedi')) > 0 ~ 'Flowers',
      sapply(description_f,function(x) is_keyword_in(x,'aldarabars')) > 0 ~ 'Aldarabars',
      sapply(description_f,function(x) is_keyword_in(x,'lennolenno')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'bergamo')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'darzaikskile')) > 0 ~ 'Darza',
      sapply(description_f,function(x) is_keyword_in(x,'milsriga')) > 0 ~ 'Mils',
      sapply(description_f,function(x) is_keyword_in(x,'wwwlvlvstpasutijumanrsiapigulatviaassebbankaa')) > 0 ~ '220LV',
      sapply(description_f,function(x) is_keyword_in(x,'starbucksmilan')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'lakannariga')) > 0 ~ 'LaKanna',
      sapply(description_f,function(x) is_keyword_in(x,'aibalbianello')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'varennait')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'autostradalepero')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'italilenno')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'chefexpressspaorioalserio')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'apollokino')) > 0 ~ 'Apollokino',
      sapply(description_f,function(x) is_keyword_in(x,'veselibasmeistarsriga')) > 0 ~ 'Fizio',
      sapply(description_f,function(x) is_keyword_in(x,'dynastyveikals')) > 0 ~ 'Dynastyveikals',
      sapply(description_f,function(x) is_keyword_in(x,'dalmaljsiaaptieka')) > 0 ~ 'Aptieka',
      sapply(description_f,function(x) is_keyword_in(x,'aulalvtallinn')) > 0 ~ 'Aula',
      sapply(description_f,function(x) is_keyword_in(x,'laikaelpasia')) > 0 ~ 'Yoga',
      sapply(description_f,function(x) is_keyword_in(x,'rocketbeancafe')) > 0 ~ 'Rocketbeancafe',
      sapply(description_f,function(x) is_keyword_in(x,'euroaptieka')) > 0 ~ 'Aptieka',
      sapply(description_f,function(x) is_keyword_in(x,'picerijacilipizza')) > 0 ~ 'Cillipica',
      sapply(description_f,function(x) is_keyword_in(x,'lidogalerijariga')) > 0 ~ 'Lido',
      sapply(description_f,function(x) is_keyword_in(x,'veikalsmego')) > 0 ~ 'Mego',
      sapply(description_f,function(x) is_keyword_in(x,'kafejnicanr')) > 0 ~ 'Cafe',
      sapply(description_f,function(x) is_keyword_in(x,'madaraecocosmetics')) > 0 ~ 'Madara',
      sapply(description_f,function(x) is_keyword_in(x,'jysktcsaga')) > 0 ~ 'Jysk',
      sapply(description_f,function(x) is_keyword_in(x,'paypalveronikamaran')) > 0 ~ 'Stretching',
      sapply(description_f,function(x) is_keyword_in(x,'abebooks')) > 0 ~ 'Books',
      sapply(description_f,function(x) is_keyword_in(x,'gemossmukusalas')) > 0 ~ 'Gemoss',
      sapply(description_f,function(x) is_keyword_in(x,'sportabode')) > 0 ~ 'Sportabode',
      sapply(description_f,function(x) is_keyword_in(x,'decathlonriga')) > 0 ~ 'Decathlon',
      sapply(description_f,function(x) is_keyword_in(x,'agrisvaselans')) > 0 ~ 'Transfers',
      sapply(description_f,function(x) is_keyword_in(x,'ludoveikals')) > 0 ~ 'Braingames',
      sapply(description_f,function(x) is_keyword_in(x,'heberiga')) > 0 ~ 'Gifts',
      sapply(description_f,function(x) is_keyword_in(x,'dmxgroup')) > 0 ~ 'Donnahome',
      sapply(description_f,function(x) is_keyword_in(x,'tetrekins')) > 0 ~ 'TET',
      sapply(description_f,function(x) is_keyword_in(x,'duninrveikals')) > 0 ~ 'Gifts',
      sapply(description_f,function(x) is_keyword_in(x,'omnivariga')) > 0 ~ 'Onmiva',
      sapply(description_f,function(x) is_keyword_in(x,'apothekariga')) > 0 ~ 'Aptieka',
      sapply(description_f,function(x) is_keyword_in(x,'globussriga')) > 0 ~ 'Books',
      sapply(description_f,function(x) is_keyword_in(x,'karkadeterbatas')) > 0 ~ 'Gifts',
      sapply(description_f,function(x) is_keyword_in(x,'cleancontrol')) > 0 ~ 'Cleaners',
      sapply(description_f,function(x) is_keyword_in(x,'piparssagadreilini')) > 0 ~ 'Pipars',
      sapply(description_f,function(x) is_keyword_in(x,'pepcoriga')) > 0 ~ 'Pepco',
      sapply(description_f,function(x) is_keyword_in(x,'veikalstopriga')) > 0 ~ 'Top',
      sapply(description_f,function(x) is_keyword_in(x,'menessaptieka')) > 0 ~ 'Aptieka',
      sapply(description_f,function(x) is_keyword_in(x,'veikalsrudrariga')) > 0 ~ 'Rudra',
      sapply(description_f,function(x) is_keyword_in(x,'flixbus')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'ledakcijas')) > 0 ~ 'Ledakcijas',
      sapply(description_f,function(x) is_keyword_in(x,'tshirtstoreorigo')) > 0 ~ 'Gifts',
      sapply(description_f,function(x) is_keyword_in(x,'bookdepository')) > 0 ~ 'Books',
      sapply(description_f,function(x) is_keyword_in(x,'tcgalleriariga')) > 0 ~ 'tcgalleriariga',
      sapply(description_f,function(x) is_keyword_in(x,'kalvecoffee')) > 0 ~ 'kalvecoffee',
      sapply(description_f,function(x) is_keyword_in(x,'kamelijasaptieka')) > 0 ~ 'Aptieka',
      sapply(description_f,function(x) is_keyword_in(x,'garazariga')) > 0 ~ 'Garaza',
      sapply(description_f,function(x) is_keyword_in(x,'danijalatvija')) > 0 ~ 'Danija',
      sapply(description_f,function(x) is_keyword_in(x,'camelliaikrig')) > 0 ~ 'Dzija',
      sapply(description_f,function(x) is_keyword_in(x,'merkeladruka')) > 0 ~ 'Gifts',
      sapply(description_f,function(x) is_keyword_in(x,'levande')) > 0 ~ 'Levande',
      sapply(description_f,function(x) is_keyword_in(x,'izstaderiga')) > 0 ~ 'Izstade',
      sapply(description_f,function(x) is_keyword_in(x,'copypro')) > 0 ~ 'copypro',
      sapply(description_f,function(x) is_keyword_in(x,'masazassantaivule')) > 0 ~ 'Massage',
      sapply(description_f,function(x) is_keyword_in(x,'newyorker')) > 0 ~ 'NewYorker',
      sapply(description_f,function(x) is_keyword_in(x,'personigofinansukonsultacija')) > 0 ~ 'FiancialConsultant',
      sapply(description_f,function(x) is_keyword_in(x,'beinertssia')) > 0 ~ 'Vet',
      sapply(description_f,function(x) is_keyword_in(x,'rdelectronics')) > 0 ~ 'RDElectronics',
      sapply(description_f,function(x) is_keyword_in(x,'ahtielizabetes')) > 0 ~ 'AHTI',
      sapply(description_f,function(x) is_keyword_in(x,'rekinsdziksterbatas')) > 0 ~ 'Utilities',
      sapply(description_f,function(x) is_keyword_in(x,'siashevlad')) > 0 ~ 'Home, Electronics',
      sapply(description_f,function(x) is_keyword_in(x,'noblewine')) > 0 ~ 'NobleWine',
      sapply(description_f,function(x) is_keyword_in(x,'valisitsi')) > 0 ~ 'Dentist',
      sapply(description_f,function(x) is_keyword_in(x,'pusdienurestoransonzeriga')) > 0 ~ 'Worklunch',
      sapply(description_f,function(x) is_keyword_in(x,'valuedate')) > 0 ~ 'Commisions',
      sapply(description_f,function(x) is_keyword_in(x,'terasia')) > 0 ~ 'TeraSIA',
      sapply(description_f,function(x) is_keyword_in(x,'attraderig')) > 0 ~ 'ATTrade',
      sapply(description_f,function(x) is_keyword_in(x,'cameocameo')) > 0 ~ 'Gifts',
      sapply(description_f,function(x) is_keyword_in(x,'dentaklinikariga')) > 0 ~ 'Dentist',
      sapply(description_f,function(x) is_keyword_in(x,'interflor')) > 0 ~ 'Flowers',
      sapply(description_f,function(x) is_keyword_in(x,'cenuklubs')) > 0 ~ 'Cenuklubs',
      sapply(description_f,function(x) is_keyword_in(x,'ctservicesriga')) > 0 ~ 'Online shopping',
      sapply(description_f,function(x) is_keyword_in(x,'rxtirdznieciba')) > 0 ~ 'ElkorFood',
      sapply(description_f,function(x) is_keyword_in(x,'jyskspice')) > 0 ~ 'Jysk',
      sapply(description_f,function(x) is_keyword_in(x,'veikalsdzirnavurig')) > 0 ~ 'Tiger',
      sapply(description_f,function(x) is_keyword_in(x,'zvaigzneabc')) > 0 ~ 'ZvaigzneABC',
      sapply(description_f,function(x) is_keyword_in(x,'gemoss')) > 0 ~ 'Gemoss',
      sapply(description_f,function(x) is_keyword_in(x,'nopirktlv')) > 0 ~ 'Online shopping',
      sapply(description_f,function(x) is_keyword_in(x,'manillaveikals')) > 0 ~ 'Manilla',
      sapply(description_f,function(x) is_keyword_in(x,'montonspice')) > 0 ~ 'Monton',
      sapply(description_f,function(x) is_keyword_in(x,'burgeriingaskudre')) > 0 ~ 'Burgers',
      sapply(description_f,function(x) is_keyword_in(x,'sumuprajastyle')) > 0 ~ 'Jewelry',
      sapply(description_f,function(x) is_keyword_in(x,'lindex')) > 0 ~ 'Lindex',
      sapply(description_f,function(x) is_keyword_in(x,'beatesdavana')) > 0 ~ 'Gifts',
      sapply(description_f,function(x) is_keyword_in(x,'pinkidsia')) > 0 ~ 'Hairdresser',
      sapply(description_f,function(x) is_keyword_in(x,'jahonts')) > 0 ~ 'Jewelry',
      sapply(description_f,function(x) is_keyword_in(x,'manillaaudeju')) > 0 ~ 'Manilla',
      sapply(description_f,function(x) is_keyword_in(x,'magnolijaszieds')) > 0 ~ 'Flowers',
      sapply(description_f,function(x) is_keyword_in(x,'ritarosmesonline')) > 0 ~ 'Morningroutine',
      sapply(description_f,function(x) is_keyword_in(x,'musmajaterbate')) > 0 ~ 'Musmaja',
      sapply(description_f,function(x) is_keyword_in(x,'ubercom')) > 0 ~ 'Vacation',	
      sapply(description_f,function(x) is_keyword_in(x,'kostimilv')) > 0 ~ 'KostimiLV',
      sapply(description_f,function(x) is_keyword_in(x,'oyshoriga')) > 0 ~ 'Oysho',
      sapply(description_f,function(x) is_keyword_in(x,'masazasantaivule')) > 0 ~ 'Massage',
      sapply(description_f,function(x) is_keyword_in(x,'healthygamer')) > 0 ~ 'Healthygamer',
      sapply(description_f,function(x) is_keyword_in(x,'petcity')) > 0 ~ 'Petcity',
      sapply(description_f,function(x) is_keyword_in(x,'meimelinveikals')) > 0 ~ 'Jewelry',
      sapply(description_f,function(x) is_keyword_in(x,'bubertskafejnica')) > 0 ~ 'Buberts',
      sapply(description_f,function(x) is_keyword_in(x,'metaorigo')) > 0 ~ 'Meta',
      sapply(description_f,function(x) is_keyword_in(x,'xsollaownd')) > 0 ~ 'Owned',
      sapply(description_f,function(x) is_keyword_in(x,'veikalsidille')) > 0 ~ 'Idille',
      sapply(description_f,function(x) is_keyword_in(x,'spcissinternationalsecoverath')) > 0 ~ 'Shopping',
      sapply(description_f,function(x) is_keyword_in(x,'magnlijaszieds')) > 0 ~ 'Flowers',
      sapply(description_f,function(x) is_keyword_in(x,'eventwmqmwevents')) > 0 ~ 'Eventplanner',
      sapply(description_f,function(x) is_keyword_in(x,'siafmund')) > 0 ~ 'LED',
      sapply(description_f,function(x) is_keyword_in(x,'henrymoon')) > 0 ~ 'Henrymoon',
      sapply(description_f,function(x) is_keyword_in(x,'ziedotlv')) > 0 ~ 'Ziedot',
      sapply(description_f,function(x) is_keyword_in(x,'tcskymorerestora')) > 0 ~ 'Skynmore',
      sapply(description_f,function(x) is_keyword_in(x,'militaryshop')) > 0 ~ 'Militaryshop',
      sapply(description_f,function(x) is_keyword_in(x,'zaneparuma')) > 0 ~ 'Online shopping',
      sapply(description_f,function(x) is_keyword_in(x,'latvijastekstils')) > 0 ~ 'Online shopping',
      sapply(description_f,function(x) is_keyword_in(x,'tetrekina')) > 0 ~ 'TET',
      sapply(description_f,function(x) is_keyword_in(x,'mcdonalds')) > 0 ~ 'mcdonalds',
      sapply(description_f,function(x) is_keyword_in(x,'datoriunprogrammas')) > 0 ~ 'Datoriunprogrammas',
      sapply(description_f,function(x) is_keyword_in(x,'vairaksaulesdzirnavu')) > 0 ~ 'VairakSaules',
      sapply(description_f,function(x) is_keyword_in(x,'latvijasaptieka')) > 0 ~ 'Latvijasaptieka',
      sapply(description_f,function(x) is_keyword_in(x,'restoranstokkram')) > 0 ~ 'Restaurant',
      sapply(description_f,function(x) is_keyword_in(x,'thisplacedosentneed')) > 0 ~ 'ThisPlace',
      sapply(description_f,function(x) is_keyword_in(x,'eventmorevalmiera')) > 0 ~ 'Eventmore',
      sapply(description_f,function(x) is_keyword_in(x,'tornisriga')) > 0 ~ 'Tornis',
      sapply(description_f,function(x) is_keyword_in(x,'alfahm')) > 0 ~ 'H&M',
      sapply(description_f,function(x) is_keyword_in(x,'paymentspasts')) > 0 ~ 'Online shopping',
      sapply(description_f,function(x) is_keyword_in(x,'ariandrasia')) > 0 ~ 'Flowers',
      sapply(description_f,function(x) is_keyword_in(x,'amzncombill')) > 0 ~ 'Online shopping',
      sapply(description_f,function(x) is_keyword_in(x,'braingameslvriga')) > 0 ~ 'BrainGames',
      sapply(description_f,function(x) is_keyword_in(x,'croppsatekles')) > 0 ~ 'Cropp',
      sapply(description_f,function(x) is_keyword_in(x,'gemoriga')) > 0 ~ 'Shoes',
      sapply(description_f,function(x) is_keyword_in(x,'veikalsenjoythegame')) > 0 ~ 'Gifts',
      sapply(description_f,function(x) is_keyword_in(x,'tcgalleriardzirnavriga')) > 0 ~ 'Shopping',
      sapply(description_f,function(x) is_keyword_in(x,'boarbbq')) > 0 ~ 'BoarBBQ',
      sapply(description_f,function(x) is_keyword_in(x,'kilomaxveikals')) > 0 ~ 'KiloMax',
      sapply(description_f,function(x) is_keyword_in(x,'muffinsandmore')) > 0 ~ 'Muffinsandmore',
      sapply(description_f,function(x) is_keyword_in(x,'tabaccheria')) > 0 ~ 'Smokeshop',
      sapply(description_f,function(x) is_keyword_in(x,'vapehouse')) > 0 ~ 'Smokeshop',
      sapply(description_f,function(x) is_keyword_in(x,'kabinettwineshop')) > 0 ~ 'KabinetWine',
      sapply(description_f,function(x) is_keyword_in(x,'gertrudesnirvana')) > 0 ~ 'Nirvana',
      sapply(description_f,function(x) is_keyword_in(x,'beerabargertrudes')) > 0 ~ 'Beerabar',
      sapply(description_f,function(x) is_keyword_in(x,'idille')) > 0 ~ 'Idille',
      sapply(description_f,function(x) is_keyword_in(x,'pilsetrestoranslapsas')) > 0 ~ 'Foxhouse',
      sapply(description_f,function(x) is_keyword_in(x,'mrfox')) > 0 ~ 'MrFox',
      sapply(description_f,function(x) is_keyword_in(x,'kolonnaaudeju')) > 0 ~ 'Kolonna',
      sapply(description_f,function(x) is_keyword_in(x,'veronikamaranina')) > 0 ~ 'Stretching',
      sapply(description_f,function(x) is_keyword_in(x,'martinabernadavana')) > 0 ~ 'Gifts',
      sapply(description_f,function(x) is_keyword_in(x,'cydonialv')) > 0 ~ 'Cydonia',
      sapply(description_f,function(x) is_keyword_in(x,'bistroriga')) > 0 ~ 'Bistro',
      sapply(description_f,function(x) is_keyword_in(x,'coffeenation')) > 0 ~ 'CoffeeNation',
      sapply(description_f,function(x) is_keyword_in(x,'lidoalfa')) > 0 ~ 'Lido',
      sapply(description_f,function(x) is_keyword_in(x,'cielavinaancecelmina')) > 0 ~ 'Gifts',
      sapply(description_f,function(x) is_keyword_in(x,'gandrsdarbnica')) > 0 ~ 'Gandrs',
      sapply(description_f,function(x) is_keyword_in(x,'laciterbatas')) > 0 ~ 'Laci',
      sapply(description_f,function(x) is_keyword_in(x,'omiobus')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'ecolines')) > 0 ~ 'Transport',
      sapply(description_f,function(x) is_keyword_in(x,'rigaspasstacija')) > 0 ~ 'Online shopping',
      sapply(description_f,function(x) is_keyword_in(x,'kozyeats')) > 0 ~ 'Kozyeats',
      sapply(description_f,function(x) is_keyword_in(x,'caffeine')) > 0 ~ 'Caffeine',
      sapply(description_f,function(x) is_keyword_in(x,'bosaburgers')) > 0 ~ 'Bosaburgers',
      sapply(description_f,function(x) is_keyword_in(x,'darzenilv')) > 0 ~ 'DarzeniLV',
      sapply(description_f,function(x) is_keyword_in(x,'kumodeorigo')) > 0 ~ 'Kumode',
      sapply(description_f,function(x) is_keyword_in(x,'kafejnicazidsrezekne')) > 0 ~ 'ZidsRezekne',
      sapply(description_f,function(x) is_keyword_in(x,'eservissdpd')) > 0 ~ 'Online shopping',
      sapply(description_f,function(x) is_keyword_in(x,'betterbreadriga')) > 0 ~ 'Betterbread',
      sapply(description_f,function(x) is_keyword_in(x,'vissatputaidaba')) > 0 ~ 'Vissatputaidaba',
      sapply(description_f,function(x) is_keyword_in(x,'europarkdzirnavu')) > 0 ~ 'Europark',
      sapply(description_f,function(x) is_keyword_in(x,'veikalsperlotava')) > 0 ~ 'Jewelry',
      sapply(description_f,function(x) is_keyword_in(x,'kebabbbb')) > 0 ~ 'kebab',
      sapply(description_f,function(x) is_keyword_in(x,'kebabsartjomsjersovs')) > 0 ~ 'kebab',
      sapply(description_f,function(x) is_keyword_in(x,'vuelinginflightsales')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'boatservicelenno')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'reitanvilniusvilnius')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'lidldienstleistungmuench')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'ticketshopbernch')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'hesburger')) > 0 ~ 'Hesburger',
      sapply(description_f,function(x) is_keyword_in(x,'palladiumrig')) > 0 ~ 'Palladium',
      sapply(description_f,function(x) is_keyword_in(x,'vertigoabmukmukusa')) > 0 ~ 'AnnasDarzs',
      sapply(description_f,function(x) is_keyword_in(x,'chatkaseriga')) > 0 ~ 'Chatrestaurant',
      sapply(description_f,function(x) is_keyword_in(x,'smokemaster')) > 0 ~ 'Smokeshop',
      sapply(description_f,function(x) is_keyword_in(x,'nurmebar')) > 0 ~ 'Nurmebar',
      sapply(description_f,function(x) is_keyword_in(x,'ogaslvkvaldemara')) > 0 ~ 'OgasLV',
      sapply(description_f,function(x) is_keyword_in(x,'candypopalfa')) > 0 ~ 'Candypop',
      sapply(description_f,function(x) is_keyword_in(x,'googlegooglestorage')) > 0 ~ 'GoogleStorage',
      sapply(description_f,function(x) is_keyword_in(x,'ausmenakebabs')) > 0 ~ 'Ausmanis',
      sapply(description_f,function(x) is_keyword_in(x,'veikalskalsnava')) > 0 ~ 'Flowers',
      sapply(description_f,function(x) is_keyword_in(x,'amfoodcarnikavas')) > 0 ~ 'AMFood',
      sapply(description_f,function(x) is_keyword_in(x,'wwwtaxigo')) > 0 ~ 'Taxigo',
      sapply(description_f,function(x) is_keyword_in(x,'duniveikals')) > 0 ~ 'Duni',
      sapply(description_f,function(x) is_keyword_in(x,'eirovinskrbarona')) > 0 ~ 'Eirovins',
      sapply(description_f,function(x) is_keyword_in(x,'stendersveikals')) > 0 ~ 'Stenders',
      sapply(description_f,function(x) is_keyword_in(x,'difspaagenziadiffusioo')) > 0 ~ 'Vacation',
      sapply(description_f,function(x) is_keyword_in(x,'terbatasaptieka')) > 0 ~ 'Aptieka',
      
      
      T ~ 'Other'
    ),

    
    category_main = case_when(category %in% c('Rimi','Maxima','Ogas', 'Drogas','Mego','Top', 'ElkorFood','Idille',
                                              'DarzeniLV','OgasLV','AMFood') ~ 'Groceries',
                              
                              category %in% c('Restart','Terra','Worklunch','kebab') ~ 'Lunch at work',
                              
                              category %in% c('Circle K','Narvesen','Cadets') ~ 'Convenience shops',
                              
                              category %in% c('Wolt','Lulu','FoodFactory','Lido') ~ 'Food delivery',
                              
                              category %in% c('Olearys','stblackteraseriga','Darza',
                                              'LaKanna','Rocketbeancafe','Cillipica',
                                              'Cafe','Pipars','kalvecoffee','Garaza',
                                              'NobleWine', 'Burgers', 'Buberts','Skynmore','mcdonalds',
                                              'VairakSaules','Restaurant','Kukotava',
                                              'Mulberry','Tinto','Ezitismigla','vairksaules','andaluzijassuns',
                                              'Rosemarine','Rigaskebabs','Mils','ThisPlace','Tornis',
                                              'BoarBBQ','Muffinsandmore','KabinetWine','Foxhouse','MrFox',
                                              'Cydonia','Bistro','CoffeeNation','Nirvana','Kozyeats','Caffeine',
                                              'Bosaburgers','ZidsRezekne','Betterbread','Hesburger','AnnasDarzs',
                                              'Chatrestaurant','Ausmanis','Eirovins') ~ 'Eating out',
                              
                              category %in% c('Makonis', 'Gimlet','Herbarijs','Manana','Aldarabars','AHTI',
                                              'Beerabar','Nurmebar') ~ 'Bars',
                              
                              category %in% c('Adobe',
                                              'Factile',
                                              'Apple',
                                              'PeopleFitness',
                                              'Steezystudio',
                                              'Amazon',
                                              'Audible',
                                              'Nordvpn',
                                              'Dropbox',
                                              'Amazonvideo',
                                              'Secretscentbox',
                                              'Patreon',
                                              'GoogleStorage') ~ 'Subscriptions',
                              
                              category %in% c('Elkor','Stockman','Peek and Cloppenburg', 'Amoralle','Online shopping',
                                              'Ikea',
                                              'Games',
                                              'Asos',
                                              "H&M",
                                              'Mango',
                                              'Danija',
                                              'Sexystyle',
                                              'Zara',
                                              'Douglas',
                                              'Accessorize',
                                              'Apavi40plus',
                                              'Akropole',
                                              'Domina',
                                              'Zalando',
                                              'Ledakcijas',
                                              'Reserved',
                                              'Donnaveikals',
                                              'Nikeoutletstore',
                                              'Sportland',
                                              'AmazonMarketplace',
                                              'Downstreet',
                                              'wwwmuzikasveikals',
                                              'Vipa',
                                              '220LV',
                                              'Rudra',
                                              'Bomond',
                                              'Sportabode',
                                              'Decathlon',
                                              'Braingames',
                                              'Onmiva',
                                              'Pepco',
                                              'tcgalleriariga',
                                              'Dzija',
                                              'NewYorker',
                                              'Monton',
                                              'Jewelry',
                                              'Lindex',
                                              'KostimiLV',
                                              'Oysho',
                                              'Meta',
                                              'Cropp',
                                              'Shoes',
                                              'KiloMax',
                                              'Smokeshop',
                                              'Kumode'
                                              ) ~ 'Shopping',
                              
                              category %in% c('Bolt', 'Yandex','Transport','Europark','Taxigo') ~ 'Taxi',
                              
                              category %in% c('LabasPreces','Euronics','PC','Ksenukai','Jysk',
                                              'Silvertree','Electrolux','Depo','Easypot','Dinozoo',
                                              'Flowers','Gemoss','Donnahome','Cleaners','copypro','Vet',
                                              'RDElectronics', 'TeraSIA', 'ATTrade', 'Cenuklubs', 'Tiger',
                                              'Manilla','Musmaja','Petcity','Owned','LED','Henrymoon',
                                              'Datoriunprogrammas','Duni','Stenders') ~ 'Home, Electronics',
                              
                              category %in% c('Bilesuserviss','Ekase','Bilesuparadize',
                                              'Balticticketing','Forumcinemas','Arcade',
                                              'Apollokino','Aula','Izstade','Eventmore',
                                              'Gandrs','Vissatputaidaba','Palladium') ~ 'Culture&Relax',
                              
                              category %in% c('Booking') ~ 'Vacation',
                              
                              category %in% c('Hairdresser','Eraesthetic','Skinpro',
                                              'Beautymarket','Kristiana','ESPA','Iherb','Pedi',
                                              'Masazufabrika','Hairrigariga','Sunnybeautylounge',
                                              'Silicenko','Notino','Beautyfor','Dynastyveikals',
                                              'Madara','Levande','WOW','Massage','Kolonna') ~ 'Beauty',
                              
                              category %in% c('PremiumMedical','Benuaptieka','Capitalclinic',
                                              'Trufit','Fizio','Aptieka','Yoga','Stretching', 'Dentist',
                                              'Latvijasaptieka') ~ 'Doctor, Medicine, Health',
                              
                              category %in% c('LedusSkola','DrivingLessons','Books','Shroomshop','FiancialConsultant',
                                              'ZvaigzneABC','Morningroutine', 'Healthygamer','BrainGames','Pension') ~ 'Self-Development',
                              
                              category %in% c('Latloto','Poker') ~ 'Gambling',
                              
                              category %in% c('Electricity','TET') ~ 'Utilities',
                              
                              category %in% c('Photopgraphy',
                                              'wwwziedotlv',
                                              'Eventplanner',
                                              'Ziedot',
                                              'Militaryshop',
                                              'Laci',
                                              'Candypop') ~ 'Gifts',
                              
                              
                              T ~ category),
    
    category_major = case_when(
      category_main %in% c('Utilities','Rent','PhoneBill') ~ 'Bills',
      category_main %in% c('Groceries','Lunch at work', 'Subscriptions','Commisions') ~ 'Living Expenses',
      category_main %in% c('Hotel', 'Beauty', 'Doctor, Medicine, Health', 'Culture&Relax',
                           'Self-Development') ~ 'Self-care Expenses',
      category_main %in% c('Shopping', 'Bars', 'Convenience shops','Food delivery, Takeout',
                           'Eating out','Gambling','Home, Electronics','Poker','Taxi','Revolut',
                           'Gifts') ~ 'Indulging Expenses',
      T ~ category_main
    )
    ) 

bank_stmt <- bank_stmt %>% filter(transaction_date >= ymd(20210301),
                                  amount > 0)

# How many gave you categorized so far?

table(bank_stmt$category)/nrow(bank_stmt)


# In the process of keyword searching, you want to refine categories so that "Other" contains less 

bank_stmt %>% filter(category == 'Other') %>% 
  arrange(desc(amount)) %>% 
  select(description_f,description, type, amount, transaction_yearmonth) %>% as_tibble() %>%  View()

bank_stmt %>% filter(category == 'Other') %>% 
  arrange(desc(amount)) %>% 
  select(description_f,description, type, amount, transaction_yearmonth) %>%
  filter(month(transaction_yearmonth) == 7) %>% as_tibble() %>%  View()

table(bank_stmt$description_f[bank_stmt$category == 'Other']) %>% View()
